version: "3"
services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: bradery
      MYSQL_USER: bradery
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports: 
      - '3306:3306'
  adminer: 
    image: adminer
    ports:
      - '8000:8080'

